apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 6000
      targetPort: 6000
      nodePort: 30007  # You can choose any port between 30000-32767